server:
  port: 80

spring:
  application:
    name: blue-bank
  datasource:
    url: jdbc:h2:mem:blue_bank-dev-db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console.enabled: true